### ISSUE TITLE
Replace `num_rows` with len?

### ISSUE THREAD

**Issue by stefanv** [dsten/datascience#107]
The standard way to query containers for number of entries is ``len(table)``.  Consider removing ``num_rows``?

**Comment by stefanv** [comment]
``len`` counts columns, so closing this.

**Comment by deculler** [comment]
Yes.  We had quite a lot of design discussion around that last summer.
This choice reflects the view that Table is fundamentally an ordered
collection of columns.  The primordial version took the other position.
However, one could argue that python intrinsics don't really contemplate
multidimensional structures.   One might argue that len should alias to
num_cols so that the container takes a more symmetric position, but maps
the dominate one to len()

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley
