### ISSUE TITLE
Should we use Zenhub?

### ISSUE THREAD

**Issue by SamLau95** [dsten/datascience#38]
What do you guys think about using [Zenhub](https://www.zenhub.io/) for our workflow? I've noticed that it's a little challenging to manage multiple issues in different states of progress because they're all in one big list. Zenhub adds a layer of functionality on top of Github while preserving existing functionality for those who don't want to use it.

Here's a couple problems and how Zenhub handles them.

**It's hard to see which issues are important (we should work on immediately) and which we're putting off for later.**
Zenhub has multiple columns (called pipelines) to file issues under called "Backlog", "In progress", "New Issues", etc.

**We have multiple repos are being worked on but each one has its own issue list.**
You can use one Zenhub board to view and manage issues from multiple repos.

Personally, I've used Zenhub before for a bunch of projects and liked it a lot more than the simple Issue list Github provides. But, there's always an overhead of getting used to the new technology.

@papajohn @alvinwan

**Comment by papajohn** [comment]
It's a good suggestion, but I'm just not ready to learn a new project
management system at the moment. So, if I don't have to use it, then I'm
happy to have everyone else adopt it. Otherwise, I think we're stuck with
milestones to group issues together with a deadline and priority.

I do agree that working across multiple repos is annoying... just suffering
from tech overload and I need to focus on getting things done for the next
few weeks.

-John

**Comment by alvinwan** [comment]
Wow, looks really nice. Never knew something like this existed.

Neat suggestion. Maybe at a future date though, per Prof. DeNero's comment.
