### ISSUE TITLE
Histogram from values (or intervals) and counts

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#54]
From Ani:

Is it possible to have hist draw a histogram based on a distribution table?

E.g. the inputs are intervals and the proportions in each interval (adding up to 100%). Output is a histogram.

At the moment hist takes the raw data as its input. We could simply generate the right number of values at the center of each interval, and provide that as the dataset.

I'm asking because it will be very helpful when students find bad histograms in the newspaper or journal articles and try to fix them. They won't have the raw data. They'll just have the distribution, badly represented. To fix the representation, they could work with the distribution by hand as in Stat 2/20/21, but could we do better in our course?

See the following for an example; scroll down till you see the bar graph.
http://www.cdc.gov/mmwr/preview/mmwrhtml/rr58e0821a1.htm

**Comment by papajohn** [comment]
Yes, we can add a method to build a histogram from one column of values and one column of counts. I think that's sufficient.

**Comment by papajohn** [comment]
I got close — you can now build a histogram from counts.

https://github.com/dsten/datascience/blob/master/datascience/tables.py#L880

However, we still need a way to generate two histograms from two columns of counts, and I'm not sure what the syntax should look like. E.g., imagine a three column table of `ages`, the counts of `males` by age and the counts of `females` by age. What expression should compare them?

**Comment by SamLau95** [comment]
Was talking with Ani today and she mentioned the same thing.

Let's suppose we have a table like this:


Age  | Male Counts | Female Counts
10   | 2           | 3
20   | 13          | 10
30   | 8           | 13
40   | 5           | 12
50   | 3           | 2
60   | 2           | 0
70   | 0           | 0
80   | 1           | 0

What if we instead of `counts='Male Counts'`to specify that the Male Counts column are the count values we have something like `count_bins='Age'`? Essentially, passing in the column used for bins instead of passing in the column used for counts? Then `hist` would produce two histograms in this case where the bins are the ages and the counts are the male/female counts.

This would also make the `overlay` argument more consistent.

**Comment by deculler** [comment]
Table.hist used to return a histogram as a table.  That was very handy.  Bins becomes one of the columns.  Then normalizing it by the total count gives a discrete probability distribution.  Total variational distance doesn't make much sense on histograms.  Right?

**Comment by davidwagner** [comment]
See #83 for my current take on this -- sounds very similar to what David Culler is talking about.

**Comment by deculler** [comment]
There is a version in table2hist branch.  See if you like it.   des ja
vous...  It is back to what hist used to do.  With the overlay, it creates
a column of the bins.  Otherwise, it creates a bin column for each
histogram.  Thus the table contains just what is in the pictures.  It
generates names for the columns similar to what pivot does.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by deculler** [comment]
The counts is still there.  It just passes through to pyplot.hist.  You can
also pass normed=True and it will normalize it and produce the discrete
distribution.  Are friends at scipy already thought through all this.  We
pretty much just needed to not get in the way.  numpy.histogram does all
these things too.  pyplot.hist passes them through because you need them...
yep sure do.

I also through in Table.bar so that you could do something reasonable with
plotting the resulting tables.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley
