### ISSUE TITLE
Sampling with and without replacement from rows

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#8]

**Comment by alvinwan** [comment]
What's this mean? I can work on it.

**Comment by mijordan3** [comment]
This is setting the stage for the inferential part of the course.  It's
important.

We need a function or set of functions that, given a table with n rows,
will return another table
with k rows, where the rows have been selected randomly (see more on this
below).  In general
k will be any integer less than or equal to n.  An important special case,
indeed the one that we
will rely on again and again, is when k is equal to n.

"Selected randomly" means one of two things.  We can sample with
replacement, which means
that each of the n rows has equal (1/n) probability of being selected at
each of the k steps.  We
can sample without replacement, which means that at the first step has of
the n rows has equal
(

**Comment by mijordan3** [comment]
Oops, hit the send button too soon.  Continuing on...

This is setting the stage for the inferential part of the course.  It's
important.

We need a function or set of functions that, given a table with n rows,
will return another table
with k rows, where the rows have been selected randomly (see more on this
below).  In general
k will be any integer less than or equal to n.  An important special case,
indeed the one that we
will rely on again and again, is when k is equal to n.

"Selected randomly" means one of two things.  We can sample with
replacement, which means
that each of the n rows has equal (1/n) probability of being selected at
each of the k steps.  We
can sample without replacement, which means that at the first step has of
the n rows has equal
(1/n) probability of being chosen, at the next step each of the remaining
n-1 unselected rows has
probably 1/(n-1) of being selected, and so on until k rows have been
chosen.  In the special case
in which k is equal to n, this is equivalent to doing a random permutation
of the rows of the original
table.

After you've finished with this, a nice follow-on could be *weighted*
sampling, where there is a
vector of weights, w = (w_1, w_2, ..., w_n), such that 0 <= w_i <= 1, and
sum_i w_i = 1, and the
sampling is done with these weights rather than with uniform probabilities.

Mike

**Comment by alvinwan** [comment]
Oh wow, I see. Thanks for the detailed explanation - I'll get started.
