### ISSUE TITLE
Histograms should be a computational object

### ISSUE THREAD

**Issue by davidwagner** [dsten/datascience#83]
Right now, a histogram is a picture.  All you can do with it is display it, but you can't manipulate it programmatically.

One of the principles in this class is that histograms are how we think about distributions; they are our stand-in for a distribution (especially an empirical distribution).  It seems like it might be useful to make a histogram a computational object, one that can be programmatically accessed and operated on.

In particular, it seems like it might be elegant to think of a histogram as a table with one row per bin and two columns: one identifying the bin, one with the frequency/count/probability for that bin.  I suggest that we have two methods: one that computes a histogram-table from a table (binning things etc.), and another that plots a histogram-table visually.

Here's one example of a candidate design:

    Table.histogram(column_label, bins=None, counts=None, **vargs)
        Bins the values in the specified column, and returns a HistogramTable for them.
        vargs can be bins=..., range=..., normed=... (True by default)

    HistogramTable.display(**vargs)
        Plots the histogram and makes a picture.
        vargs might contain variable options that control the layout of the picture, e.g., color=....

HistogramTable is a subclass of Table with two columns, 'value' and 'probability', and all the usual methods -- it can be treated just like a table -- but it also supports the extra method display() to make a picture.  (Or maybe three columns, 'left endpoint' and 'right endpoint' and 'probability'?)

This would let you do something like tbl.histogram(...).display(...) to get a picture, but also let you do tbl.histogram(...) to get a histogram that you can work with programmatically: compute variation distance on, draw samples from, etc.

**Comment by deculler** [comment]
I am running into this very concern.

Table.hist used to return a table - in addition to displaying the pretty
picture.  pyplot.hist is designed to support this; it returns counts, bins,
and patches.  It has args from normalizing it and all that.

We used to convert that into a table and return in.  This seems to have
gotten lost in the clean up.  I assume Ani's desire for counts is really
this.  But you don't just want a pretty picture, you want the data
structure.  Then you can subtract column from another and get the VAR.  If
you really don't want the picture, we could have a no_display arg.

Numpy.histogram is very similar, but has slightly different return values.
Using only the pyplot interface avoids any subtle differences in the plot
and the returned table.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by deculler** [comment]
I produced a version of Table.hist that returns the resulting histogram as
a table.  Fixed some bugs in hist along the way.  Of course, to look at one
you really want a bar chart rather than a graph, so I made one of those
too.  (It takes column labels, like pyplot.bar, but it would make more
sense if none is give to just generate a sequence of integers.)

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by SamLau95** [comment]
@davidwagner Does #85 address your issue here?

**Comment by papajohn** [comment]
I think `bin` and the new `counts` option of `hist` does the trick, so closing the issue. If it's not what you want, then feel free to re-open.

**Comment by deculler** [comment]
I agree with John.  Continuing this trend with pivot_bin takes us quite a
ways further into territory that would otherwise require the nested and
complicated structure of dataframes.  Pivot_hist previously returned the
resulting histogram as a table - it had to because pivot allowed one to
express things that would not fit into a table but hist brought it back.
Separating viz from computing tables is cleaner.  Return a hist table is
analogous to stats.  There are now a bunch of examples in demo that take
this to some real examples.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley
